stages:
  - build
  - test

include:
  - project: 'edquity/gitlab-ops'
    file: 'token_cache_build.yml'

branch:
  extends: .build
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always
  variables:
    CREATE_LATEST_IMAGE: ""

main:
  extends: .build
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  variables:
    CREATE_LATEST_IMAGE: --destination $CI_REGISTRY_IMAGE:latest

test-coverage:
  stage: test
  image: golang:alpine3.13
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - pwd
    # - go test -v ./tfd/test -coverpkg=./... | go-junit-report -set-exit-code > report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
